const upcomingEventsInfo = [
    {
        id: 1,
        eventType: "upcoming",
        name: 'International Band Music Concert',
        fulldate: '14',
        fullday: 'Tuesday',
        fullmonth: 'June',
        date: '14th',
        day: 'Tue',
        month: 'Jun',
        year: '2021',
        startingTime: '4:00PM',
        endingTime: '9:00PM',
        location: '36 Guild Street London, UK',
        place: 'Gala Convention Center',
        organizer: 'Ashfak Sayem',
        organizerFollowing: '200',
        organizerFollowers: '457',
        organizerAbout: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time.',
        organizerReviews: [
            {
                reviewId: 1,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Rocks Velkeinjen",
                reviewDay: "10",
                reviewMonth: "Feb",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 2,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Freda V. Southwick",
                reviewDay: "14",
                reviewMonth: "Nov",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 3,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Samantha R. Wade",
                reviewDay: "08",
                reviewMonth: "Mar",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 4,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Bryant M. Romero",
                reviewDay: "01",
                reviewMonth: "Jan",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
        ],
        organizerDp: require("../Assets/OrganizerPics/OrganizerDp1.png"),
        eventImage: require("../Assets/EventsImages/Event1.png"),
        going1: require("../Assets/ProfilePics/Person2.png"),
        going2: require("../Assets/ProfilePics/Person3.png"),
        going3: require("../Assets/ProfilePics/Person4.png"),
        howManyGoing: '+20 Going',
        ticketprice: '120',
        about: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time. Food from local food trucks will be available for purchase.'
    },
    {
        id: 2,
        eventType: "upcoming",
        name: 'Jo Malone London’s Mother’s Day Presents',
        fulldate: '10',
        fullday: 'Sunday',
        fullmonth: 'July',
        date: '10th',
        day: 'Sun',
        month: 'Jul',
        year: '2021',
        startingTime: '5:00PM',
        endingTime: '10:00PM',
        location: 'Radius Gallery • Santa Cruz, CA',
        place: 'Gala Convention Center',
        organizer: 'Emma Amelia',
        organizerFollowing: '250',
        organizerFollowers: '507',
        organizerAbout: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time.',
        organizerReviews: [
            {
                reviewId: 1,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Laura D. Grady",
                reviewDay: "10",
                reviewMonth: "Feb",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 2,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "David B. Kersten",
                reviewDay: "14",
                reviewMonth: "Nov",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 3,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Nancy S. Mead",
                reviewDay: "08",
                reviewMonth: "Mar",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 4,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Rick K. Cordero",
                reviewDay: "01",
                reviewMonth: "Jan",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
        ],
        organizerDp: require("../Assets/OrganizerPics/OrganizerDp2.png"),
        eventImage: require("../Assets/EventsImages/Event5.png"),
        going1: require("../Assets/ProfilePics/Person2.png"),
        going2: require("../Assets/ProfilePics/Person1.png"),
        going3: require("../Assets/ProfilePics/Person4.png"),
        howManyGoing: '+20 Going',
        ticketprice: '150',
        about: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time. Food from local food trucks will be available for purchase.'
    },
    {
        id: 3,
        eventType: "non",
        name: 'A Virtual Evening of Smooth Jazz',
        fulldate: '1',
        fullday: 'Saturday',
        fullmonth: 'May',
        date: '1st',
        day: 'Sat',
        month: 'May',
        year: '2021',
        startingTime: '8:00PM',
        endingTime: '12:00PM',
        location: 'Lot 13 • Oakland, CA',
        place: 'Royal Marquee Complex',
        organizer: 'William James',
        organizerFollowing: '400',
        organizerFollowers: '757',
        organizerAbout: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time.',
        organizerReviews: [
            {
                reviewId: 1,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Laura D. Grady",
                reviewDay: "10",
                reviewMonth: "Feb",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 2,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "David B. Kersten",
                reviewDay: "14",
                reviewMonth: "Nov",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 3,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Nancy S. Mead",
                reviewDay: "08",
                reviewMonth: "Mar",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 4,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Rick K. Cordero",
                reviewDay: "01",
                reviewMonth: "Jan",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
        ],
        organizerDp: require("../Assets/OrganizerPics/OrganizerDp3.png"),
        eventImage: require("../Assets/EventsImages/Event6.png"),
        going1: require("../Assets/ProfilePics/Person2.png"),
        going2: require("../Assets/ProfilePics/Person1.png"),
        going3: require("../Assets/ProfilePics/Person4.png"),
        howManyGoing: '+10 Going',
        ticketprice: '100',
        about: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time. Food from local food trucks will be available for purchase.'
    },
    {
        id: 4,
        eventType: "nearby",
        name: 'Women’s Leadership Conference 2021',
        fulldate: '6',
        fullday: 'Monday',
        fullmonth: 'Auguest',
        date: '6th',
        day: 'Mon',
        month: 'Aug',
        year: '2021',
        startingTime: '4:00PM',
        endingTime: '6:00PM',
        location: '53 Bush St • San Francisco, CA',
        place: 'Serene Event Complex',
        organizer: 'Noah James',
        organizerFollowing: '10',
        organizerFollowers: '142',
        organizerAbout: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time.',
        organizerReviews: [
            {
                reviewId: 1,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Tomas S. Stevens",
                reviewDay: "10",
                reviewMonth: "Feb",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 2,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Renato M. Duncan",
                reviewDay: "14",
                reviewMonth: "Nov",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 3,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Gary M. Pilkington",
                reviewDay: "08",
                reviewMonth: "Mar",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 4,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Virginia R. Roberson",
                reviewDay: "01",
                reviewMonth: "Jan",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
        ],
        organizerDp: require("../Assets/OrganizerPics/OrganizerDp4.png"),
        eventImage: require("../Assets/EventsImages/Event3.png"),
        going1: require("../Assets/ProfilePics/Person2.png"),
        going2: require("../Assets/ProfilePics/Person1.png"),
        going3: require("../Assets/ProfilePics/Person4.png"),
        howManyGoing: '+50 Going',
        ticketprice: '50',
        about: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time. Food from local food trucks will be available for purchase.'
    },
    {
        id: 5,
        eventType: "nearby",
        name: 'International Kids Safe Parents Night Out',
        fulldate: '23',
        fullday: 'Friday',
        fullmonth: 'April',
        date: '23th',
        day: 'Fri',
        month: 'Apr',
        year: '2021',
        startingTime: '9:00AM',
        endingTime: '12:00PM',
        location: 'Lot 13 • Oakland, CA',
        place: 'Royal Majestic Hall',
        organizer: 'Sophia Benjamin',
        organizerFollowing: '50',
        organizerFollowers: '550',
        organizerAbout: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time.',
        organizerReviews: [
            {
                reviewId: 1,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Rob H. Sanchez",
                reviewDay: "10",
                reviewMonth: "Feb",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 2,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Jean B. Wilhelm",
                reviewDay: "14",
                reviewMonth: "Nov",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 3,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "John B. Prentice",
                reviewDay: "08",
                reviewMonth: "Mar",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 4,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Christopher A. Manske",
                reviewDay: "01",
                reviewMonth: "Jan",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
        ],
        organizerDp: require("../Assets/OrganizerPics/OrganizerDp2.png"),
        eventImage: require("../Assets/EventsImages/Event4.png"),
        going1: require("../Assets/ProfilePics/Person2.png"),
        going2: require("../Assets/ProfilePics/Person1.png"),
        going3: require("../Assets/ProfilePics/Person4.png"),
        howManyGoing: '+15 Going',
        ticketprice: '120',
        about: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time. Food from local food trucks will be available for purchase.'
    },
    {
        id: 6,
        eventType: "non",
        name: 'Collectivity Plays the Music of Jimi',
        fulldate: '12',
        fullday: 'Tuesday',
        fullmonth: 'May',
        date: '12th',
        day: 'Tue',
        month: 'May',
        year: '2021',
        startingTime: '8:00PM',
        endingTime: '10:00PM',
        location: 'Longboard Margarita Bar',
        place: 'Pearl Event Complex',
        organizer: 'Ava Liam',
        organizerFollowing: '100',
        organizerFollowers: '824',
        organizerAbout: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time.',
        organizerReviews: [
            {
                reviewId: 1,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Laura D. Grady",
                reviewDay: "10",
                reviewMonth: "Feb",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 2,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Andrew M. Mullins",
                reviewDay: "14",
                reviewMonth: "Nov",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 3,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "John E. Burgess",
                reviewDay: "08",
                reviewMonth: "Mar",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 4,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Rick K. Cordero",
                reviewDay: "01",
                reviewMonth: "Jan",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
        ],
        organizerDp: require("../Assets/OrganizerPics/OrganizerDp1.png"),
        eventImage: require("../Assets/EventsImages/Event2.png"),
        going1: require("../Assets/ProfilePics/Person2.png"),
        going2: require("../Assets/ProfilePics/Person1.png"),
        going3: require("../Assets/ProfilePics/Person4.png"),
        howManyGoing: '+15 Going',
        ticketprice: '100',
        about: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time. Food from local food trucks will be available for purchase.'
    },
    {
        id: 7,
        eventType: "non",
        name: 'International Gala Music Festival',
        fulldate: '25',
        fullday: 'Sunday',
        fullmonth: 'June',
        date: '25th',
        day: 'Sun',
        month: 'Jun',
        year: '2021',
        startingTime: '8:30PM',
        endingTime: '10:30PM',
        location: '36 Guild Street London, UK',
        place: 'Sapphire Banquet Hall',
        organizer: 'Olivia William',
        organizerFollowing: '43',
        organizerFollowers: '627',
        organizerAbout: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time.',
        organizerReviews: [
            {
                reviewId: 1,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Elizabeth A. Vice",
                reviewDay: "10",
                reviewMonth: "Feb",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 2,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "David B. Kersten",
                reviewDay: "14",
                reviewMonth: "Nov",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 3,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Marilyn D. Burt",
                reviewDay: "08",
                reviewMonth: "Mar",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 4,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Brenda T. Mullins",
                reviewDay: "01",
                reviewMonth: "Jan",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
        ],
        organizerDp: require("../Assets/OrganizerPics/OrganizerDp3.png"),
        eventImage: require("../Assets/EventsImages/Event7.png"),
        going1: require("../Assets/ProfilePics/Person2.png"),
        going2: require("../Assets/ProfilePics/Person1.png"),
        going3: require("../Assets/ProfilePics/Person4.png"),
        howManyGoing: '+100 Going',
        ticketprice: '200',
        about: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time. Food from local food trucks will be available for purchase.'
    },
    {
        id: 8,
        eventType: "nearby",
        name: 'Battle of the bands',
        fulldate: '25',
        fullday: 'Sunday',
        fullmonth: 'November',
        date: '25th',
        day: 'Sun',
        month: 'Nov',
        year: '2021',
        startingTime: '8:00PM',
        endingTime: '11:00PM',
        location: '36 Guild Street London, UK',
        place: 'Sapphire Banquet Hall',
        organizer: 'Karen Aujla',
        organizerFollowing: '43',
        organizerFollowers: '627',
        organizerAbout: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time.',
        organizerReviews: [
            {
                reviewId: 1,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Laura D. Grady",
                reviewDay: "10",
                reviewMonth: "Feb",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 2,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Ernestine B. Mills",
                reviewDay: "14",
                reviewMonth: "Nov",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 3,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "James R. Rickett",
                reviewDay: "08",
                reviewMonth: "Mar",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
            {
                reviewId: 4,
                reviewPic: require("../Assets/ReviewsProfilePics/Pic1.png"),
                reviewName: "Marvin L. Yi",
                reviewDay: "01",
                reviewMonth: "Jan",
                reviewComment: "Cinemas is the ultimate experience to see new movies in Gold Class or Vmax. Find a cinema near you."
            },
        ],
        organizerDp: require("../Assets/OrganizerPics/OrganizerDp5.png"),
        eventImage: require("../Assets/EventsImages/Event8.png"),
        going1: require("../Assets/ProfilePics/Person2.png"),
        going2: require("../Assets/ProfilePics/Person1.png"),
        going3: require("../Assets/ProfilePics/Person4.png"),
        howManyGoing: '+200 Going',
        ticketprice: '250',
        about: 'Enjoy your favorite dishe and a lovely your friends and family and have a great time. Food from local food trucks will be available for purchase.'
    },
]
export default upcomingEventsInfo;